stages:
  - npm_build

include:
  - remote: "https://releases.jfrog.io/artifactory/jfrog-cli/gitlab/v2/.setup-jfrog-unix.yml"

build-job:
  stage: npm_build
  image: node:lts
  variables:
    JF_URL: "${JF_URL}"
    JF_USERNAME: "${JF_USERNAME}"
    BUILD_NAME: "gitlabs-node-goat"
    BUILD_ID: "${CI_PIPELINE_ID}"
    JF_PROJECT: "${JF_PROJECT}"
    # NPM_JF_RT_REPO: ""
    # DOCKER_JF_RT_REPO: ""
  script:
    - !reference [.setup_jfrog, script] # install JF-CLI v2
    - jf --version